# Generated by Django 2.0.2 on 2018-03-03 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contacts', '0002_auto_20180303_0253'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
    ]
