# Generated by Django 2.0.2 on 2018-03-03 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contacts', '0003_auto_20180303_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
